name: CI:core

on:
  push:
  pull_request:
    branches: [main]

jobs:
  core-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - working-directory: ./packages/core
        run: |
          npm ci
          npm run build --if-present
          npm test
